name       : tlp
version    : '1.1'
release    : 11
source     :
    - https://github.com/linrunner/TLP/archive/1.1.tar.gz : 76e1a091eed1055f7af75f49621be51ed41b1e8f872eeb9506c0749060fd1019
license    : GPL-2.0
component  : system.utils
summary    : Linux Advanced Power Management
description: |
    Linux Advanced Power Management
builddeps  :
    - hdparm
    - iw
    - rfkill
rundeps    :
    - linux-tools-x86_energy_perf_policy
    - rfkill
setup      : |
    %patch -p1 < $pkgfiles/0001-Don-t-enable-tlp-service-on-virtualised-platforms.patch
    # Disable Audio Power Save
    sed -i 's:SOUND_POWER_SAVE_ON_BAT=1:SOUND_POWER_SAVE_ON_BAT=0:g' default
    # Disable USB Autosuspend
    sed -i 's:USB_AUTOSUSPEND=1:USB_AUTOSUSPEND=0:g' default
    # Disable Wireless Power Management
    sed -i 's:WIFI_PWR_ON_BAT=on:WIFI_PWR_ON_BAT=off:g' default
build      : |
    export TLP_LIBDIR='%libdir%'
    export TLP_SBIN='/usr/sbin'
    export TLP_ULIB='%libdir%/udev/'
    %make
install    : |
    export TLP_NO_INIT='1'
    export TLP_SYSD='%libdir%/systemd/system/'
    export TLP_WITH_SYSTEMD='1'
    %make_install install-man
    mkdir -p $installdir/%libdir%
    mv $installdir/lib/udev $installdir/%libdir%/
    mv $installdir/usr/lib/* $installdir/%libdir%/
    rm -rf $installdir/lib $installdir/usr/lib

    # Enable by default, users can disable now with systemctl mask tlp
    install -D -d -m 00755 $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv ../tlp.service $installdir/%libdir%/systemd/system/multi-user.target.wants
