name       : tlp
version    : 0.8
release    : 1
source     :
    - https://github.com/linrunner/TLP/archive/0.8.tar.gz : d5c0423fde7247cc519001caebd60e538ff5ef2be9456d2049303eef4da1aae3
license    : GPL-2.0
summary    : Linux Advanced Power Management
description: |
    Linux Advanced Power Management
builddeps  :
    - hdparm
    - iw
    - rfkill
rundeps:
    - rfkill
build      : |
    %make TLP_LIBDIR=%libdir% TLP_SBIN=/usr/sbin TLP_ULIB=%libdir%/udev/ \
        TLP_SYSD=/etc/systemd/system/ TLP_WITH_SYSTEMD=1
install    : |
    %make_install
    mkdir -p $installdir/%libdir%
    mv $installdir/lib/udev $installdir/%libdir%/
    mv $installdir/usr/lib/* $installdir/%libdir%/
    rm -rf $installdir/lib $installdir/usr/lib
