name       : tlp
version    : 1.5.0
release    : 17
source     :
    - https://github.com/linrunner/TLP/archive/1.5.0.tar.gz : b5f08f00d535c26abc49b336b4c7264c6e5fb7bc3de8054eaabeebdd00e0760e
license    : GPL-2.0-only
component  : system.utils
summary    : Linux Advanced Power Management
description: |
    Linux Advanced Power Management, customized for Solus:
    - Disabled Wi-Fi power saving mode on battery
    - Disabled audio power saving for Intel HDA, AC97 devices
    - Disabled  USB autosuspend feature
builddeps  :
    - hdparm
    - iw
rundeps    :
    - linux-tools-x86_energy_perf_policy
setup      : |
    %apply_patches
build      : |
    export TLP_LIBDIR='%libdir%'
    export TLP_SBIN='/usr/sbin'
    export TLP_ULIB='%libdir%/udev/'
    %make
install    : |
    export TLP_NO_INIT='1'
    export TLP_SYSD='%libdir%/systemd/system/'
    export TLP_ULIB='%libdir%/udev/'
    export TLP_WITH_ELOGIND='0'
    %make_install install-man
    rm -rf $installdir/var

    # Enable by default, users can disable now with systemctl mask tlp
    install -Ddm 00755 $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv ../tlp.service $installdir/%libdir%/systemd/system/multi-user.target.wants
