name       : tlp
version    : 1.2.1
release    : 13
source     :
    - https://github.com/linrunner/TLP/archive/1.2.1.tar.gz : 0fa43c2be7d42223646c6271eb823174076a92c9cea5740c24b5e9e8404c9765
license    : GPL-2.0-only
component  : system.utils
summary    : Linux Advanced Power Management
description: |
    Linux Advanced Power Management
builddeps  :
    - hdparm
    - iw
rundeps    :
    - linux-tools-x86_energy_perf_policy
setup      : |
    %patch -p1 < $pkgfiles/0001-Don-t-enable-tlp-service-on-virtualised-platforms.patch
    # Disable Audio Power Save
    sed -i 's:SOUND_POWER_SAVE_ON_BAT=1:SOUND_POWER_SAVE_ON_BAT=0:g' default
    # Disable USB Autosuspend
    sed -i 's:USB_AUTOSUSPEND=1:USB_AUTOSUSPEND=0:g' default
    # Disable Wireless Power Management
    sed -i 's:WIFI_PWR_ON_BAT=on:WIFI_PWR_ON_BAT=off:g' default
build      : |
    export TLP_LIBDIR='%libdir%'
    export TLP_SBIN='/usr/sbin'
    export TLP_ULIB='%libdir%/udev/'
    %make
install    : |
    export TLP_NO_INIT='1'
    export TLP_SYSD='%libdir%/systemd/system/'
    export TLP_WITH_SYSTEMD='1'
    %make_install install-man
    mkdir -p $installdir/%libdir%
    mv $installdir/lib/udev $installdir/%libdir%/
    rm -rf $installdir/lib

    # Enable by default, users can disable now with systemctl mask tlp
    install -D -d -m 00755 $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv ../tlp.service $installdir/%libdir%/systemd/system/multi-user.target.wants
